// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: mesh/mesh.proto

package mesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeshMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MessageType       uint32                 `protobuf:"varint,1,opt,name=messageType,proto3" json:"messageType,omitempty"`            // 0=ADAPTER_DATA, 1=MASTER_BEACON, 2=ENROLLMENT, 3=JOIN_ACK
	DataType          int32                  `protobuf:"zigzag32,2,opt,name=dataType,proto3" json:"dataType,omitempty"`                // zigzag: -1=UNKNOWN, 0=PIR, 1=WIFI, 2=LED, 3=SERIAL
	OriginMacAddress  []byte                 `protobuf:"bytes,3,opt,name=originMacAddress,proto3" json:"originMacAddress,omitempty"`   // 6 bytes
	TargetMacAddress  []byte                 `protobuf:"bytes,4,opt,name=targetMacAddress,proto3" json:"targetMacAddress,omitempty"`   // 6 bytes
	LastHopMacAddress []byte                 `protobuf:"bytes,5,opt,name=lastHopMacAddress,proto3" json:"lastHopMacAddress,omitempty"` // 6 bytes
	Data              []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                           // up to 12 bytes
	HopCount          uint32                 `protobuf:"varint,7,opt,name=hopCount,proto3" json:"hopCount,omitempty"`
	EpochNum          uint32                 `protobuf:"varint,8,opt,name=epochNum,proto3" json:"epochNum,omitempty"`                    // sender boot epoch (was field 9 — CORRECTED to match firmware)
	SeqNum            uint32                 `protobuf:"varint,9,opt,name=seqNum,proto3" json:"seqNum,omitempty"`                        // per-boot sequence counter (was field 10 — CORRECTED)
	ProtoVersion      uint32                 `protobuf:"varint,10,opt,name=protoVersion,proto3" json:"protoVersion,omitempty"`           // must be 1 for v1 messages (was field 8 — CORRECTED)
	PublicKey         []byte                 `protobuf:"bytes,11,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // enrollment/join_ack: 32-byte Curve25519 public key
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MeshMessage) Reset() {
	*x = MeshMessage{}
	mi := &file_mesh_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshMessage) ProtoMessage() {}

func (x *MeshMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshMessage.ProtoReflect.Descriptor instead.
func (*MeshMessage) Descriptor() ([]byte, []int) {
	return file_mesh_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *MeshMessage) GetMessageType() uint32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *MeshMessage) GetDataType() int32 {
	if x != nil {
		return x.DataType
	}
	return 0
}

func (x *MeshMessage) GetOriginMacAddress() []byte {
	if x != nil {
		return x.OriginMacAddress
	}
	return nil
}

func (x *MeshMessage) GetTargetMacAddress() []byte {
	if x != nil {
		return x.TargetMacAddress
	}
	return nil
}

func (x *MeshMessage) GetLastHopMacAddress() []byte {
	if x != nil {
		return x.LastHopMacAddress
	}
	return nil
}

func (x *MeshMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MeshMessage) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *MeshMessage) GetEpochNum() uint32 {
	if x != nil {
		return x.EpochNum
	}
	return 0
}

func (x *MeshMessage) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *MeshMessage) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

func (x *MeshMessage) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_mesh_mesh_proto protoreflect.FileDescriptor

const file_mesh_mesh_proto_rawDesc = "" +
	"\n" +
	"\x0fmesh/mesh.proto\x12\x04mesh\"\xf8\x02\n" +
	"\vMeshMessage\x12 \n" +
	"\vmessageType\x18\x01 \x01(\rR\vmessageType\x12\x1a\n" +
	"\bdataType\x18\x02 \x01(\x11R\bdataType\x12*\n" +
	"\x10originMacAddress\x18\x03 \x01(\fR\x10originMacAddress\x12*\n" +
	"\x10targetMacAddress\x18\x04 \x01(\fR\x10targetMacAddress\x12,\n" +
	"\x11lastHopMacAddress\x18\x05 \x01(\fR\x11lastHopMacAddress\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1a\n" +
	"\bhopCount\x18\a \x01(\rR\bhopCount\x12\x1a\n" +
	"\bepochNum\x18\b \x01(\rR\bepochNum\x12\x16\n" +
	"\x06seqNum\x18\t \x01(\rR\x06seqNum\x12\"\n" +
	"\fprotoVersion\x18\n" +
	" \x01(\rR\fprotoVersion\x12\x1d\n" +
	"\n" +
	"public_key\x18\v \x01(\fR\tpublicKeyB,Z*github.com/superbrobenji/motionServer/meshb\x06proto3"

var (
	file_mesh_mesh_proto_rawDescOnce sync.Once
	file_mesh_mesh_proto_rawDescData []byte
)

func file_mesh_mesh_proto_rawDescGZIP() []byte {
	file_mesh_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_mesh_proto_rawDesc), len(file_mesh_mesh_proto_rawDesc)))
	})
	return file_mesh_mesh_proto_rawDescData
}

var file_mesh_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mesh_mesh_proto_goTypes = []any{
	(*MeshMessage)(nil), // 0: mesh.MeshMessage
}
var file_mesh_mesh_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mesh_mesh_proto_init() }
func file_mesh_mesh_proto_init() {
	if File_mesh_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_mesh_proto_rawDesc), len(file_mesh_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mesh_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_mesh_proto_depIdxs,
		MessageInfos:      file_mesh_mesh_proto_msgTypes,
	}.Build()
	File_mesh_mesh_proto = out.File
	file_mesh_mesh_proto_goTypes = nil
	file_mesh_mesh_proto_depIdxs = nil
}
